App\Entity\User:
    attributes:
        id:
            groups: [ 'user:read', 'user:write' ]
        email:
            groups: [ 'user:read', 'user:write' ]
        roles:
            groups: [ 'user:read', 'user:write' ]
        password:
            groups: ['user:write' ]
